### ISSUE TITLE
事务操作

### ISSUE THREAD

**Issue by rainx00** [vcycyv/go-real-world-web-app#2]
您好, 我是刚从 java spring 转过来的开发者, 对于这种分层架构 我要怎么吧多个不同service方法 放到一个事务里面呢?  (像 spring 里面只需要在 service 类上声明@transaction 就行了)

**Comment by vcycyv** [comment]
你好，我的回答未必正确，仅供参考。golang没有Spring/JPA那么强大的框架，如果你对transaction要求比较高，有两个思路，对于比较"内聚"的功能，可以在repository里单独写一个方法，手动commit transaction。这时，相当于把service的逻辑下沉到repository层。另一个思路是，在service层做compasation。比如你在表A里插入数据，成功后试图在表B里也插入数据，如果失败，手动delete掉表一里刚插入的数据。
